export enum ErrorCode {
	EMAIL_ALREADY_EXISTS = 'AUTH_001',
	INVALID_CREDENTIALS = 'AUTH_002',
	NOT_AUTHORIZED = 'AUTH_003',
	FORBIDDEN = 'AUTH_004',
	USER_NOT_FOUND = 'AUTH_005',
	SESSION_EXPIRED = 'AUTH_006',

	VALIDATION_ERROR = 'VALIDATION_001',
	INVALID_ID_FORMAT = 'VALIDATION_002',

	INTERNAL_SERVER_ERROR = 'SYSTEM_001',
	NOT_FOUND = 'SYSTEM_002',
	DATABASE_ERROR = 'SYSTEM_003',
	SERVICE_UNAVAILABLE = 'SYSTEM_004',
}
