export enum ErrorCode {
	EMAIL_ALREADY_EXISTS = 'AUTH_001',
	INVALID_CREDENTIALS = 'AUTH_002',
	NOT_AUTHORIZED = 'AUTH_003',
	FORBIDDEN = 'AUTH_004',
	USER_NOT_FOUND = 'AUTH_005',
	SESSION_EXPIRED = 'AUTH_006',

	VERIFICATION_CODE_INVALID = 'AUTH_007',
	VERIFICATION_CODE_EXPIRED = 'AUTH_008',
	TOO_MANY_ATTEMPTS = 'AUTH_009',
	PASSWORD_TOO_WEAK = 'AUTH_010',
	ACCOUNT_LOCKED = 'AUTH_011',

	MFA_REQUIRED = 'MFA_001',
	MFA_INVALID_CODE = 'MFA_002',
	MFA_NOT_ENABLED = 'MFA_003',

	OAUTH_PROVIDER_ERROR = 'OAUTH_001',
	OAUTH_ACCOUNT_ALREADY_LINKED = 'OAUTH_002',
	OAUTH_INVALID_STATE = 'OAUTH_003',

	VALIDATION_ERROR = 'VALIDATION_001',
	INVALID_ID_FORMAT = 'VALIDATION_002',
	INVALID_INPUT_DATA = 'VALIDATION_003',

	INTERNAL_SERVER_ERROR = 'SYSTEM_001',
	NOT_FOUND = 'SYSTEM_002',
	DATABASE_ERROR = 'SYSTEM_003',
	SERVICE_UNAVAILABLE = 'SYSTEM_004',
	RATE_LIMIT_EXCEEDED = 'SYSTEM_005',
}
