import { ApiProperty } from '@nestjs/swagger'
import { Type } from 'class-transformer'
import {
	IsNotEmpty,
	IsObject,
	IsString,
	MaxLength,
	MinLength,
	ValidateNested
} from 'class-validator'

export class AuthenticatorResponse {
	@ApiProperty({
		description:
			'Base64URL encoded authenticator data returned by the authenticator',
		example: 'SZYN5YgO...'
	})
	@IsString()
	@IsNotEmpty()
	public authenticatorData: string

	@ApiProperty({
		description:
			'Base64URL encoded JSON containing client challenge and origin',
		example: 'eyJ0eXBlIjoi...'
	})
	@IsString()
	@IsNotEmpty()
	public clientDataJSON: string

	@ApiProperty({
		description:
			'Base64URL encoded signature generated by the authenticator',
		example: 'MEYCIQDNDKK9...'
	})
	@IsString()
	@IsNotEmpty()
	public signature: string

	@ApiProperty({
		description:
			'Optional Base64URL user handle returned by the authenticator',
		example: 'YjMwNDM0...'
	})
	@IsString()
	public userHandle?: string
}

export class AttestationResponse {
	@ApiProperty({
		description: 'ID of the credential returned by the authenticator',
		example: 'Oh8lY...'
	})
	@IsString()
	@IsNotEmpty()
	public id: string

	@ApiProperty({
		description: 'Raw ID of the credential returned by the authenticator',
		example: 'Oh8lY...'
	})
	@IsString()
	@IsNotEmpty()
	public rawId: string

	@ApiProperty({
		description: 'Type of credential, usually public-key',
		example: 'public-key'
	})
	@IsString()
	@IsNotEmpty()
	public type: string

	@ApiProperty({
		description: 'Object containing authenticator response data',
		type: AuthenticatorResponse
	})
	@ValidateNested()
	@Type(() => AuthenticatorResponse)
	public response: AuthenticatorResponse

	@ApiProperty({
		description:
			'Authenticator attachment type (platform or cross-platform)',
		example: 'platform'
	})
	@IsString()
	public authenticatorAttachment?: string

	@ApiProperty({
		description: 'Client extension results returned by the authenticator',
		example: {}
	})
	@IsObject()
	public clientExtensionResults?: Record<string, unknown>
}

export class MfaTotpRequest {
	@ApiProperty({
		description: 'MFA Ticket',
		example: 'aca7247545d1333e155cd9bc0d94f9a8f1a49859'
	})
	@IsString()
	@IsNotEmpty()
	public ticket: string

	@ApiProperty({
		description: '6-digit code from the authentication application',
		example: '123456',
		minLength: 6,
		maxLength: 6
	})
	@IsString()
	@IsNotEmpty()
	@MinLength(6)
	@MaxLength(6)
	public totpCode: string
}

export class MfaPasskeyRequest {
	@ApiProperty({
		description: 'MFA Ticket',
		example: 'aca7247545d1333e155cd9bc0d94f9a8f1a49859'
	})
	@IsString()
	@IsNotEmpty()
	public ticket: string

	@ApiProperty({
		description: 'Attestation response from the authenticator',
		type: AttestationResponse
	})
	@ValidateNested()
	@Type(() => AttestationResponse)
	public attestationResponse: AttestationResponse
}

export class MfaRecoveryRequest {
	@ApiProperty({
		description: 'MFA Ticket',
		example: 'aca7247545d1333e155cd9bc0d94f9a8f1a49859'
	})
	@IsString()
	@IsNotEmpty()
	public ticket: string

	@ApiProperty({
		description: 'One of the recovery codes',
		example: '73e8d-67c78',
		minLength: 11,
		maxLength: 11
	})
	@IsString()
	@IsNotEmpty()
	@MinLength(11)
	@MaxLength(11)
	public recoveryCode: string
}
